app:
  image: milafrerichs/tile-server-stack
  restart: always
  command: newrelic-admin run-program gunicorn wsgi:application -b 0.0.0.0:8080 -w 3
  ports:
    - "8080"
haproxy:
  image: tutum/haproxy
  links:
    - app
  environment:
    - BACKEND_PORT=8080

nginx:
  build: ./nginx
  ports:
    - 80:80
  links:
    - haproxy
